apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.io
spec:
  group: traefik.io
  scope: Namespaced
  names:
    plural: ingressroutes
    singular: ingressroute
    kind: IngressRoute
    listKind: IngressRouteList
    shortNames:
      - ir
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: IngressRoute is the CRD for configuring HTTP routes in Traefik.
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
